### ISSUE TITLE
how to patch the field data in mongoDB collection

### ISSUE THREAD

**Issue by suryamuppalla** [satyanani40/lunarweb#9]

**Comment by satyanani40** [comment]
use following url for patch:
curl -H "Content-Type: application/json" -H "If-Match: 3b972aef419b30b56bd592692be812c1ab2d07ff" -X PATCH -i  http://127.0.0.1:8000/api/people/54b0bc37bed069248fb20ea8 -d '{"password_test":"hellow"}'

_etag is compulsory
and application type json must. because we mentioning field names in json format
